// frontend/src/components/header.tsx
import React from 'react';
import {Link} from 'react-router-dom';
import './header.css';

export default function Header() {
    return (
      <header>
        <nav>
            <div id="nav_logo">Square</div>
            <div id="nav_items">
                <ul>
                    <li><Link to='/'>Home</Link></li>
                    <li><Link to='/message'>Message</Link></li>
                    <li><Link to='/setting'>Setting</Link></li>
                    <li><a>Quit</a></li>
                </ul>
            </div>
            <div id="nav_search">
                <input placeholder="Search" />
            </div>
        </nav> 
    </header>
    );
}

// angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { SquareService } from '../square.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  constructor(private squareService: SquareService) { }

  ngOnInit(): void {
  }

  logout(): void {
    this.squareService.logout()
        .subscribe(res => window.location.href='../login.html');
  }
}

<header>
    <nav>
        <div id="nav_logo">Square</div>
        <div id="nav_items">
            <ul>
                <li><a routerLink="/">Home</a></li>
                <li><a>Message</a></li>
                <li><a routerLink="/setting">Setting</a></li>
                <li><a (click)="logout()">Quit</a></li>
            </ul>
        </div>
        <div id="nav_search">
            <input placeholder="Search">
        </div>
    </nav> 
</header>
